### PR TITLE
example of how to load NIRSx data from the mNE tutorial

### PR DESCRIPTION
**Pull request by kylemath**
I made another script file you can run from inside the virtual environment called loadExampleData.py using an example from an mne tutorial on loading the NIRx data, it loads in and plots their example data.

@kuziekj @ssheldo 
You may also want a good text editor to work in, I use sublime, and I make it so I can open it from the terminal by typing subl filename.txt, or subl . to open the current directory.

### CODE REVIEW

**Comment by kylemath** [comment]
Did it run for you?.

**Comment by ssheldo** [comment]
I used Spyder through Anaconda because Anaconda has several applications that I use in one place. So , I can use git merge to your changes to my branch or do I have to go through the base branch first?

**Comment by kylemath** [comment]
I don't understand , did my new code in this branch run when you ran it on
your computer ?.

We are trying to move from.anaconda to venv so those two won't play nice
together

**Comment by ssheldo** [comment]
I still get the error ModuleNotFoundError: No module named 'pandas'
though I did the pip install and it was fine.

**Pull request merged**
